version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: gripinvest_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: gripinvest123
      MYSQL_DATABASE: gripinvest_db
      MYSQL_USER: gripinvest_user
      MYSQL_PASSWORD: gripinvest_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - gripinvest_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gripinvest_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: gripinvest_db
      DB_USER: gripinvest_user
      DB_PASSWORD: gripinvest_pass
      JWT_SECRET: grip_invest_super_secret_jwt_key_2025_winter_internship_backend
      JWT_REFRESH_SECRET: grip_invest_refresh_secret_key_2025_winter_internship
      FRONTEND_URL: http://localhost:3000
    depends_on:
      database:
        condition: service_healthy
    networks:
      - gripinvest_network
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gripinvest_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - gripinvest_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Networks
networks:
  gripinvest_network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local